MAKAROV-AIRPORT/docker/djangopache-compose/MAKAROV/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('makarov_gp.urls')),
]

MAKAROV-AIRPORT/docker/djangopache-compose/makarov_gp/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'makarov_gp'

urlpatterns = [
    #-------------------GENERAL----------------------
    path('home/', views.HOME.defaultHomePage, name='home'),

    #-------------------USERS----------------------
    path('login/', views.USERS.loginPage, name='login'),
    path('logout/', views.USERS.logoutPage, name='logout'),
    path('register/', views.USERS.registerPage, name='register'),
    path('profile/', views.USERS.profilePage, name='profile'),
    path('flights/', views.FLIGHTS.flightsPage, name='flights'),
    path('flights_user/', views.FLIGHTS.flights_user, name="flights_user"),
    path('buy_ticket/<int:flight_id>/', views.FLIGHTS.buy_ticket, name='buy_ticket'),
    path('cancel_resa/<int:flight_id>/', views.FLIGHTS.cancel_resa, name='cancel_resa'),

    path('staff/register/', views.STAFF.registerPage, name='staff_register'),
    path('staff/login/', views.STAFF.loginPage, name='staff_login'),
    path('staff/profile/', views.STAFF.profilePage, name='staff_profile'),
    path('staff/home/', views.HOME.StaffHomePage, name="home_staff"),
    path('staff/airports/', views.AIRPORTS.addAirport, name="addAirport"),
    path('staff/airports/all/', views.AIRPORTS.showAirports, name="showAirports"),
    path('staff/airports/delete/<int:airport_id>/', views.AIRPORTS.del_airport, name="del_airport"),
    path('staff/airports/edit/<int:airport_id>/', views.AIRPORTS.edit_airport, name="edit_airport"),
    path('staff/flights/', views.FLIGHTS.addFlight, name="addFlight"),
    path('staff/flights/all/', views.FLIGHTS.showFlights, name="showFlights"),
    path('staff/flights/delete/<int:flight_id>/', views.FLIGHTS.del_flight, name="del_flight"),
    path('staff/flights/edit/<int:flight_id>/', views.FLIGHTS.edit_flight, name='edit_flight'),
    path('staff/demands/', views.CancelDemands.show_demands, name="show_demands"),
    path('staff/show_user_detail/<str:userName>', views.CancelDemands.show_user_detail, name="show_user_detail"),
    path('staff/show_flight_detail/<int:numvol>', views.CancelDemands.show_flight_detail, name="show_flight_detail"),
    path('staff/validate_demand/<int:numvol>/<str:username>/', views.CancelDemands.validate_demand, name="validate_demand"),
    path('staff/reject_demand/<int:numvol>/<str:username>/', views.CancelDemands.reject_demand, name="reject_demand"),
]

MAKAROV-AIRPORT/docker/djangopache-compose/makarov_gp/models.py
from django.db import models

# Create your models here.

MAKAROV-AIRPORT/docker/djangopache-compose/makarov_gp/forms.py
from django import forms
import random
from django.utils.translation import get_language

class ContactForm(forms.Form):
    name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'name', 'placeholder': 'Your Name'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form. control', 'id': 'email', 'placeholder': 'Your Email'}))
    subject = forms.CharField(max_length=150, widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'subject', 'placeholder': 'Subject'}))
    message = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 5, 'placeholder': 'Message'}))


class UserCreationForm(forms.Form):

    first_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'w-100'}),
        max_length=100,
        label='First Name',
        help_text='Enter your first name.'
    )

    last_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'w-100'}),
        max_length=100,
        label='Last Name',
        help_text='Enter your last name.'
    )

    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'w-100'}),
        max_length=100,
        label='Username',
        help_text='Enter your desired username.'
    )

    email = forms.EmailField(
        widget=forms.EmailInput(attrs={'class': 'w-100'}),
        label='Email',
        help_text='Enter a valid email address.'
    )

    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'w-100'}),
        label='Password',
        help_text='Enter a strong password.'
    )

    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'w-100'}),
        label='Confirm Password',
        help_text='Enter the same password for verification.'
    )


    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        password2 = cleaned_data.get("password2")
        if password and password2 and password != password2:
            self.add_error('password2', "Passwords do not match")
        return cleaned_data


class UserModificationForm(forms.Form):
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'w-75 disabled'}),
        max_length=100,
        label='First Name :',
        help_text='Enter your first name.'
    )

    last_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'w-75 disabled'}),
        max_length=100,
        label='Last Name :',
        help_text='Enter your last name.'
    )

    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'w-75 disabled'}),
        max_length=100,
        label='Username :',
        help_text='Enter your desired username.'
    )

    email = forms.EmailField(
        widget=forms.EmailInput(attrs={'class': 'w-75 disabled'}),
        label='Email :',
        help_text='Enter a valid email address.'
    )

class AirportForm(forms.Form):
    nom = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'nom', 'placeholder': 'Airport Name'}))
    code_pays = forms.CharField(max_length=3, widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'code_pays', 'placeholder': 'Airport Country Code'}))
    fuseau = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'fuseau', 'placeholder': 'Airport Timezone'}))


class FlightForm(forms.Form):
    date_depart = forms.DateField(label='Date Depart', required=True, widget=forms.DateInput(attrs={'type': 'date'}))
    date_arrivee = forms.DateField(label='Date Arrivee', required=True, widget=forms.DateInput(attrs={'type': 'date'}))
    heure_depart = forms.TimeField(label='Heure Depart', required=True, widget=forms.TimeInput(attrs={'type': 'time'}))
    heure_arrivee = forms.TimeField(label='Heure Arrivee', required=True, widget=forms.TimeInput(attrs={'type': 'time'}))
    prix = forms.DecimalField(label='Prix', required=True, max_digits=10, decimal_places=2)

MAKAROV-AIRPORT/docker/djangopache-compose/makarov_gp/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from django.utils import translation
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from .forms import UserCreationForm, UserModificationForm, AirportForm, FlightForm
import requests, json
import time
import random
from .nats_utils import publish_reservation, PublishAnnulationDemande, PublishAnnulationValidation

# Create your views here.
class HOME(TemplateView):
    def defaultHomePage(request):
        
        if request.method == "POST":
            print("POSTING THE FILTER FORM")
            airports = requests.get('http://web-rest-4:8004/structure/infos/aeroports/')
            airports = airports.json()
            #print(f"Airports : {airports}")

            flights = requests.get('http://web-rest-2:8002/vols/infos/')
            flights = flights.json()
            #print(f"Flights : {flights}")

            # Create a dictionary to quickly lookup airport names by id
            airport_dict = {airport['id']: airport['nom'] for airport in airports}

            # Add new attributes to each flight
            for flight in flights:
                flight['aeroport_depart_nom'] = airport_dict.get(flight['aeroport_depart_ref'], 'Unknown')
                flight['aeroport_arrivee_nom'] = airport_dict.get(flight['aeroport_arrivee_ref'], 'Unknown')

            departure = request.POST.get('departure')
            arrival = request.POST.get('arrival')
            date = request.POST.get('date')
            adults = request.POST.get('adults')
            kids = request.POST.get('kids')
            travel_class = request.POST.get('class')

            filtered_flights = []

            for flight in flights:
                if departure and flight['aeroport_depart_ref'] != int(departure):
                    continue
                if arrival and flight['aeroport_arrivee_ref'] != int(arrival):
                    continue
                if date and flight['date_depart'] != date:
                    continue
                if travel_class and flight['type'] != travel_class:
                    continue

                # If all conditions are satisfied, keep the flight
                filtered_flights.append(flight)

            flights = filtered_flights

            print(f"Flights : {flights}")

            return render(request, 'flights/flight_list.html', {'flights': flights, 'airports': airports})

        airports = requests.get('http://web-rest-4:8004/structure/infos/aeroports/')
        airports = airports.json()

        return render(request, 'general/index.html', {'airports': airports})
    
    def StaffHomePage(request):
        user = request.session.get('user')
        print(f"User : {user}")
        if user is not None:
            if user['is_superuser'] == True:
                return render(request, 'staff/general/index.html')
            else:
                return redirect('makarov_gp:home')
        else:
            #return to login page
            return redirect('makarov_gp:staff_login')

class FLIGHTS(TemplateView):
    def flightsPage(request, *args, **kwargs):

        airports = requests.get('http://web-rest-4:8004/structure/infos/aeroports/')
        airports = airports.json()
        #print(f"Airports : {airports}")

        flights = requests.get('http://web-rest-2:8002/vols/infos/')
        flights = flights.json()
        #print(f"Flights : {flights}")

        # Create a dictionary to quickly lookup airport names by id
        airport_dict = {airport['id']: airport['nom'] for airport in airports}

        # Add new attributes to each flight
        for flight in flights:
            flight['aeroport_depart_nom'] = airport_dict.get(flight['aeroport_depart_ref'], 'Unknown')
            flight['aeroport_arrivee_nom'] = airport_dict.get(flight['aeroport_arrivee_ref'], 'Unknown')


        if request.method == "POST":#If the user selected filters for the search
            print("POSTING THE FILTER FORM")

            print(f"Flights : {flights}")

            departure = request.POST.get('departure')
            arrival = request.POST.get('arrival')
            date = request.POST.get('date')
            adults = request.POST.get('adults')
            kids = request.POST.get('kids')
            travel_class = request.POST.get('class')

            # print(f"Departure: {departure}")
            # print(f"Arrival: {arrival}")
            # print(f"Date: {date}")
            # print(f"Adults: {adults}")
            # print(f"Kids: {kids}")
            # print(f"Travel Class: {travel_class}")

            filtered_flights = []

            for flight in flights:
                if departure and flight['aeroport_depart_ref'] != int(departure):
                    continue
                if arrival and flight['aeroport_arrivee_ref'] != int(arrival):
                    continue
                if date and flight['date_depart'] != date:
                    continue
                if travel_class and flight['type'] != travel_class:
                    continue

                # If all conditions are satisfied, keep the flight
                filtered_flights.append(flight)

            flights = filtered_flights

            print(f"Flights : {flights}")

        return render(request, 'flights/flight_list.html', {'flights': flights, 'airports': airports})

    def flights_user(request):
        user = request.session.get('user')
        if user:
            userName = user.get('username')
            print(f"User ID : {userName}")

            #Make the api call to get all of the user's reservations.
            reservations = requests.get(f'http://web-rest-3:8003/reservations/infos/user_vols/?user_ref={userName}')
            reservations = reservations.json()

            combined_reservations = []#Holds each pair reservation/vol

            #Now we concatenate the reservation and the flight details
            for reservation in reservations:
                vol_associe = requests.get(f'http://web-rest-2:8002/vols/infos/?numvol={reservation["vol_ref"]}')
                vol_associe = vol_associe.json()

                # print(f"vol associe : {vol_associe}")
                # print(f"Aeroport depart : {vol_associe[0]['aeroport_depart_ref']}")
                # print(f"Aeroport arrivee : {vol_associe[0]['aeroport_arrivee_ref']}")

                #This part below is just here to retrieve each airport's name
                departure_airport = requests.get(f'http://web-rest-4:8004/structure/infos/aeroports/{vol_associe[0]["aeroport_depart_ref"]}/')
                departure_airport_data = departure_airport.json()
                arrival_airport = requests.get(f'http://web-rest-4:8004/structure/infos/aeroports/{vol_associe[0]["aeroport_arrivee_ref"]}/')
                arrival_airport_data = arrival_airport.json()

                vol_associe[0]['aeroport_depart_nom'] = departure_airport_data['nom']
                vol_associe[0]['aeroport_arrivee_nom'] = arrival_airport_data['nom']

                combined_data = {**reservation, **vol_associe[0]}  # Assuming vol_associe returns a list with one dictionary
                combined_reservations.append(combined_data)
                
            #print(f"Reservations + Vols : {combined_reservations}")

            return render(request, 'flights/user_flights.html', {"c_reservations": combined_reservations})
        else:
            return redirect('makarov_gp:home')

    def buy_ticket(request, flight_id):#flight_id is the flight number (numvol)
        #Make the api call here to get the flight details

        user = request.session.get('user')
        if user is None:
            message = "You need to be logged-in in order to book a flight !"
            alert = "alert alert-warning"
            return render(request, "flights/message_confirmation.html", {'message': message, 'alert_style': alert})

        response = requests.get(f'http://web-rest-2:8002/vols/infos/?numvol={flight_id}')
        flight = response.json()
        flight = flight[0]
        
        print(f"Flight : {flight}")

        #Now we get the name for the departure and arrival airports
        departure_airport = requests.get(f'http://web-rest-4:8004/structure/infos/aeroports/{flight["aeroport_depart_ref"]}/')
        departure_airport_data = departure_airport.json()

        arrival_airport = requests.get(f'http://web-rest-4:8004/structure/infos/aeroports/{flight["aeroport_arrivee_ref"]}/')
        arrival_airport_data = arrival_airport.json()

        flight['aeroport_depart_nom'] = departure_airport_data['nom']
        flight['aeroport_arrivee_nom'] = arrival_airport_data['nom']

        #Now we render the page with all these infos to inform the user the flight has been booked !
        result = publish_reservation(flight_id, request.session.get('user').get('username'))
        print(f"Result unflitered : {result}")
        try:
            result = json.loads(result)
            if result['status'] == 'True':
                return render(request, 'flights/flight_detail.html', {'flight': flight})
            else:
                message = "Your bank rejected the payement."
                alert = "alert alert-warning"
                return render(request, "flights/message_confirmation.html", {'message': message, 'alert_style': alert})
        except json.decoder.JSONDecodeError:
            message = "Your bank rejected the payement."
            alert = "alert alert-warning"
            return render(request, "flights/message_confirmation.html", {'message': message, 'alert_style': alert})
            
    def cancel_resa(request, flight_id):#flight_id is the flight number (numvol)
        flight_id = flight_id

        #make api call to service to cancel the reservation.

MAKAROV-AIRPORT/docker/djangopache-compose/makarov_gp/templates/flights/flight_detail.html
{% extends "general/UI/base.html" %}

{% load static i18n %}

{% block page_title %}
    <title>Makarov Airlines - FLIGHT</title>
{% endblock page_title %}

{% block additionnal_imports %}
    <link href={% static "libs/assets/css/style-flight-detail.css" %} rel="stylesheet">
{% endblock additionnal_imports %}

{% block content%}
<div id="empty-div" style="min-height: 80px;"></div>

<main class="w-40 mx-auto rounded shadow border">
    <h3 class="mt-4 text-center">Flight N°{{ flight.numvol }}</h3>

    <div class="sub-div">
        <h4>From : </h4>
        <p>{{ flight.aeroport_depart_nom }}</p>
        <span class="date-time-sub-span">
            <p>{{ flight.date_depart }}</p>
            <p class="time-p">{{ flight.heure_depart }}</p>
        </span>
    </div>

    <div class="sub-div">
        <h4>To : </h4>
        <p>{{ flight.aeroport_arrivee_nom }}</p>
        <span class="date-time-sub-span">
            <p>{{ flight.date_arrivee }}</p>
            <p class="time-p">{{ flight.heure_arrivee }}</p>
        </span>
    </div>
    <p>Class : {{ flight.type }}</p>

    <a href={% url "makarov_gp:flights_user" %} class="link-el-cancel">
        <button class="btn btn-warning mx-auto">See My flights</button>
    </a>
</main>



{% endblock content%}

MAKAROV-AIRPORT/docker/djangopache-compose/makarov_gp/templates/flights/flight_list.html
{% extends "general/UI/base.html" %}

{% load static i18n %}

{% block page_title %}
    <title>Makarov Airlines - FLIGHTS</title>
{% endblock page_title %}

{% block additionnal_imports %}
    <link href={% static "libs/assets/css/style-flight-list.css" %} rel="stylesheet">
{% endblock additionnal_imports %}

{% block content%}

<div id="overlay" class="overlay">

</div>

<div id="empty-div" style="min-height: 80px;"></div>

<div id="form-container" class="container bg-light p-3 rounded mt-5">
    <form method="post" class="row g-3" novalidate>
        {% csrf_token %}
        <div class="col-md-4">
        <label for="trip-input" class="form-label">{% trans "Trip" %}</label>
        <select class="form-select" id="trip-input" required name="trip">
            <option selected disabled value="">{% trans "Choose..." %}</option>
            <option value="round-trip">{% trans "Round-Trip" %}</option>
            <option value="one-way">{% trans "One-way ticket" %}</option>
        </select>
        <div class="invalid-feedback">
            {% trans "Please select a valid option." %}
        </div>
        </div>


        <div class="col-md-4">
        <label for="departure-input" class="form-label">{% trans "Departure" %}</label>
        <select class="form-select" id="departure-input" required name="departure">
            <option selected disabled value="">{% trans "Choose..." %}</option>
            {% for airport in airports %}
                <option value="{{ airport.id }}">{{ airport.nom }}</option>
            {% endfor %}
        </select>
        <div class="invalid-feedback">
            {% trans "Please select a valid option." %}
        </div>
        </div>


        <div class="col-md-4">
        <label for="arrival-input" class="form-label">{% trans "Arrival" %}</label>
        <select class="form-select" id="arrival-input" required name="arrival">
            <option selected disabled value="">{% trans "Choose..." %}</option>
            {% for airport in airports %}
                <option value="{{ airport.id }}">{{ airport.nom }}</option>
            {% endfor %}
        </select>
        <div class="invalid-feedback">
            {% trans "Please select a valid option." %}
        </div>
        </div>


        <div class="col-md-3">
        <label for="date-input" class="form-label">{% trans "Date" %}</label>
        <input type="date" class="form-control" id="date-input" required name="date">
        <div class="invalid-feedback">
            {% trans "Please select a date." %}
        </div>
        </div>


        <div class="col-md-3">
        <label for="amount-adults" class="form-label">{% trans "Adults" %}</label>
        <select class="form-select" id="amount-adults" required name="adults">
            <option selected disabled value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
            <option value="5">5</option>
            <option value="6">6</option>
            <option value="7">7</option>
            <option value="8">8</option>
        </select>
        </div>


        <div class="col-md-3">
        <label for="amount-kids" class="form-label">{% trans "Kids" %}</label>
        <select class="form-select" id="amount-kids" required name="kids">
            <option selected disabled value="0">0</option>
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
            <option value="5">5</option>
            <option value="6">6</option>
            <option value="7">7</option>
            <option value="8">8</option>
        </select>
        </div>

        <div class="col-md-3">
        <label for="class" class="form-label">{% trans "Class" %}</label>
        <select class="form-select" id="class" required name="class">
            <option selected disabled value="">{% trans "Choose..." %}</option>
            <option value="E">{% trans "Economy" %}</option>
            <option value="B">{% trans "Business" %}</option>
            <option value="F">{% trans "First Class" %}</option>
        </select>
        <div class="invalid-feedback">
            {% trans "Please select a travel class." %}
        </div>
        </div>

        <div class="col-12">
        <button id="search-button" class="btn btn-primary" type="submit">{% trans "Search for a flight" %}</button>
        </div>
  </form>
</div>

<h3 id="title">Flights found</h3>

{% for flight in flights %}

    <div class="flight_line">
        <div class="row bigger-text"><p>FROM</p></div>
        <div class="line-cadre">
            <p>{{ flight.aeroport_depart_nom }}</p>
            <span class="sub-span">
                <p>{{ flight.date_depart }}</p>
                <p>{{ flight.heure_depart }}</p>
            </span>
        </div>
        <div class="row bigger-text"><p>TO</p></div>
        <div class="line-cadre">
            <p>{{ flight.aeroport_arrivee_nom }}</p>
            <span class="sub-span">
                <p>{{ flight.date_arrivee }}</p>
                <p>{{ flight.heure_arrivee }}</p>
            </span>
        </div>
        <hr class="custom-hr">
        <div class="line-cadre">
            <p>{{ flight.prix }} €</p>
            {% if flight.type == "B" %}
                <p>Business</p>
            {% elif flight.type == "E" %}
                <p>Economy</p>
            {% else %}
                <p>First Class</p>
            {% endif %}
        </div>
        <span class="middle-button">
            <a id="buy-ticket-link-{{ flight.id }}" href="{% url 'makarov_gp:buy_ticket' flight_id=flight.numvol %}">
                <button id="ticket-buy-button-{{ flight.id }}" class="btn btn-info">Buy a ticket</button>
            </a>
        </span>
    </div>

{% endfor %}

<div style="min-height: 5em;"></div>

<script>

    document.addEventListener('DOMContentLoaded', function() {
        const overlay = document.getElementById('overlay');
    
        // Iterate over each flight and attach event listeners to buy ticket buttons
        {% for flight in flights %}
            const buyTicketButton{{ flight.id }} = document.getElementById('ticket-buy-button-{{ flight.id }}');
            const buyTicketLink{{ flight.id }} = document.getElementById('buy-ticket-link-{{ flight.id }}');
    
            buyTicketButton{{ flight.id }}.addEventListener('click', function(event) {
                event.preventDefault(); // Prevent the default action of the button click
    
                // Show the overlay
                overlay.style.display = 'block';
    
                // Show "Wait while we contact your bank..." message
                const modalContent = document.createElement('div');
                modalContent.className = 'modal-content';
                modalContent.id = "modal-content";
                modalContent.innerHTML = '<p>Please wait while we contact your bank...</p>';
    
                // Append the loading image (wait.gif) if it exists
                const waitImage = document.createElement('img');
                waitImage.src = "{% static 'libs/assets/img/preloader.gif' %}"; // Adjust the path to your wait.gif
                waitImage.className = 'loading-image'; // Add a class to style the image if needed
                modalContent.appendChild(waitImage);
    
                overlay.appendChild(modalContent);
    
                // Simulate a loading delay
                setTimeout(function() {
                    // Redirect to the actual ticket-buying URL after 2 seconds
                    const ticketUrl = buyTicketLink{{ flight.id }}.getAttribute('href');
                    window.location.href = ticketUrl;
                }, 3500); // Wait for 2 seconds before redirecting
            });
        {% endfor %}
    });
</script>

{% endblock content%}

MAKAROV-AIRPORT/docker/djangopache-compose/makarov_gp/templates/flights/message_confirmation.html
{% extends "general/UI/base.html" %}

{% load static i18n %}

{% block page_title %}
    <title>Makarov Airlines - FLIGHTS</title>
{% endblock page_title %}

{% block additionnal_imports %}
    <link href={% static "libs/assets/css/style-confirmation.css" %} rel="stylesheet">
{% endblock additionnal_imports %}

{% block content%}

    <div id="empty-div" style="min-height: 80px;"></div>

    <h4 class="{{ alert_style }}"> {{ message }} </h4>

    <a href={% url "makarov_gp:home" %}><button class="btn btn-info">Back to homepage</button></a>

{% endblock content%}

MAKAROV-AIRPORT/docker/djangopache-compose/makarov_gp/templates/flights/user_flights.html
{% extends "general/UI/base.html" %}

{% load static i18n %}

{% block page_title %}
    <title>Makarov Airlines - MY FLIGHTS</title>
{% endblock page_title %}

{% block additionnal_imports %}
    <link href={% static "libs/assets/css/style-user-flight-list.css" %} rel="stylesheet">
{% endblock additionnal_imports %}

{% block content%}

<div id="empty-div" style="min-height: 80px;"></div>

{% for reservation in c_reservations %}

    {% if reservation.annulation != True %}

        <main class="cadres w-40 mx-auto rounded shadow border">
            
            <div class="row bigger-text"><p>FROM</p></div>
            <div class="line-cadre">
                <p>{{ reservation.aeroport_depart_nom }}</p>
                <span class="sub-span">
                    <p>{{ reservation.date_depart }}</p>
                    <p>{{ reservation.heure_depart }}</p>
                </span>
            </div>
            <hr class="custom-hr">
            <div class="row bigger-text"><p>TO</p></div>
            <div class="line-cadre">
                <p>{{ reservation.aeroport_arrivee_nom }}</p>
                <span class="sub-span">
                    <p>{{ reservation.date_arrivee }}</p>
                    <p>{{ reservation.heure_arrivee }}</p>
                </span>
            </div>
            <div class="line-cadre">
                <p>Class : {{ reservation.type }}</p>
                {% if reservation.demande == False %}
                    <a href={% url "makarov_gp:cancel_resa" flight_id=reservation.vol_ref %}><button class="btn btn-warning">Cancel this flight</button></a>
                {% else %}
                    <p><strong>Waiting Staff Approvement.</strong></p>
                {% endif %}

                
            </div>
        </main>

    {% endif %}

{% endfor %}

<div style="min-height: 5em;"></div>

{% endblock content%}