MAKAROV-AIRPORT/docker/djangopache-compose/MAKAROV/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('makarov_gp.urls')),
]

MAKAROV-AIRPORT/docker/djangopache-compose/makarov_gp/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'makarov_gp'

urlpatterns = [
    #-------------------GENERAL----------------------
    path('home/', views.HOME.defaultHomePage, name='home'),

    #-------------------USERS----------------------
    path('login/', views.USERS.loginPage, name='login'),
    path('logout/', views.USERS.logoutPage, name='logout'),
    path('register/', views.USERS.registerPage, name='register'),
    path('profile/', views.USERS.profilePage, name='profile'),
    path('flights/', views.FLIGHTS.flightsPage, name='flights'),
    path('flights_user/', views.FLIGHTS.flights_user, name="flights_user"),
    path('buy_ticket/<int:flight_id>/', views.FLIGHTS.buy_ticket, name='buy_ticket'),
    path('cancel_resa/<int:flight_id>/', views.FLIGHTS.cancel_resa, name='cancel_resa'),

    path('staff/register/', views.STAFF.registerPage, name='staff_register'),
    path('staff/login/', views.STAFF.loginPage, name='staff_login'),
    path('staff/profile/', views.STAFF.profilePage, name='staff_profile'),
    path('staff/home/', views.HOME.StaffHomePage, name="home_staff"),
    path('staff/airports/', views.AIRPORTS.addAirport, name="addAirport"),
    path('staff/airports/all/', views.AIRPORTS.showAirports, name="showAirports"),
    path('staff/airports/delete/<int:airport_id>/', views.AIRPORTS.del_airport, name="del_airport"),
    path('staff/airports/edit/<int:airport_id>/', views.AIRPORTS.edit_airport, name="edit_airport"),
    path('staff/flights/', views.FLIGHTS.addFlight, name="addFlight"),
    path('staff/flights/all/', views.FLIGHTS.showFlights, name="showFlights"),
    path('staff/flights/delete/<int:flight_id>/', views.FLIGHTS.del_flight, name="del_flight"),
    path('staff/flights/edit/<int:flight_id>/', views.FLIGHTS.edit_flight, name='edit_flight'),
    path('staff/demands/', views.CancelDemands.show_demands, name="show_demands"),
    path('staff/show_user_detail/<str:userName>', views.CancelDemands.show_user_detail, name="show_user_detail"),
    path('staff/show_flight_detail/<int:numvol>', views.CancelDemands.show_flight_detail, name="show_flight_detail"),
    path('staff/validate_demand/<int:numvol>/<str:username>/', views.CancelDemands.validate_demand, name="validate_demand"),
    path('staff/reject_demand/<int:numvol>/<str:username>/', views.CancelDemands.reject_demand, name="reject_demand"),
]

MAKAROV-AIRPORT/docker/djangopache-compose/makarov_gp/models.py
from django.db import models

# Create your models here.

MAKAROV-AIRPORT/docker/djangopache-compose/makarov_gp/forms.py
from django import forms
import random
from django.utils.translation import get_language

class ContactForm(forms.Form):
    name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'name', 'placeholder': 'Your Name'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form. control', 'id': 'email', 'placeholder': 'Your Email'}))
    subject = forms.CharField(max_length=150, widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'subject', 'placeholder': 'Subject'}))
    message = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 5, 'placeholder': 'Message'}))


class UserCreationForm(forms.Form):

    first_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'w-100'}),
        max_length=100,
        label='First Name',
        help_text='Enter your first name.'
    )

    last_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'w-100'}),
        max_length=100,
        label='Last Name',
        help_text='Enter your last name.'
    )

    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'w-100'}),
        max_length=100,
        label='Username',
        help_text='Enter your desired username.'
    )

    email = forms.EmailField(
        widget=forms.EmailInput(attrs={'class': 'w-100'}),
        label='Email',
        help_text='Enter a valid email address.'
    )

    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'w-100'}),
        label='Password',
        help_text='Enter a strong password.'
    )

    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'w-100'}),
        label='Confirm Password',
        help_text='Enter the same password for verification.'
    )


    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        password2 = cleaned_data.get("password2")
        if password and password2 and password != password2:
            self.add_error('password2', "Passwords do not match")
        return cleaned_data


class UserModificationForm(forms.Form):
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'w-75 disabled'}),
        max_length=100,
        label='First Name :',
        help_text='Enter your first name.'
    )

    last_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'w-75 disabled'}),
        max_length=100,
        label='Last Name :',
        help_text='Enter your last name.'
    )

    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'w-75 disabled'}),
        max_length=100,
        label='Username :',
        help_text='Enter your desired username.'
    )

    email = forms.EmailField(
        widget=forms.EmailInput(attrs={'class': 'w-75 disabled'}),
        label='Email :',
        help_text='Enter a valid email address.'
    )

class AirportForm(forms.Form):
    nom = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'nom', 'placeholder': 'Airport Name'}))
    code_pays = forms.CharField(max_length=3, widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'code_pays', 'placeholder': 'Airport Country Code'}))
    fuseau = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'fuseau', 'placeholder': 'Airport Timezone'}))


class FlightForm(forms.Form):
    date_depart = forms.DateField(label='Date Depart', required=True, widget=forms.DateInput(attrs={'type': 'date'}))
    date_arrivee = forms.DateField(label='Date Arrivee', required=True, widget=forms.DateInput(attrs={'type': 'date'}))
    heure_depart = forms.TimeField(label='Heure Depart', required=True, widget=forms.TimeInput(attrs={'type': 'time'}))
    heure_arrivee = forms.TimeField(label='Heure Arrivee', required=True, widget=forms.TimeInput(attrs={'type': 'time'}))
    prix = forms.DecimalField(label='Prix', required=True, max_digits=10, decimal_places=2)

MAKAROV-AIRPORT/docker/djangopache-compose/makarov_gp/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from django.utils import translation
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from .forms import UserCreationForm, UserModificationForm, AirportForm, FlightForm
import requests, json
import time
import random
from .nats_utils import publish_reservation, PublishAnnulationDemande, PublishAnnulationValidation

# Create your views here.
class HOME(TemplateView):
    def defaultHomePage(request):
        
        if request.method == "POST":
            print("POSTING THE FILTER FORM")
            airports = requests.get('http://web-rest-4:8004/structure/infos/aeroports/')
            airports = airports.json()
            #print(f"Airports : {airports}")

            flights = requests.get('http://web-rest-2:8002/vols/infos/')
            flights = flights.json()
            #print(f"Flights : {flights}")

            # Create a dictionary to quickly lookup airport names by id
            airport_dict = {airport['id']: airport['nom'] for airport in airports}

            # Add new attributes to each flight
            for flight in flights:
                flight['aeroport_depart_nom'] = airport_dict.get(flight['aeroport_depart_ref'], 'Unknown')
                flight['aeroport_arrivee_nom'] = airport_dict.get(flight['aeroport_arrivee_ref'], 'Unknown')

            departure = request.POST.get('departure')
            arrival = request.POST.get('arrival')
            date = request.POST.get('date')
            adults = request.POST.get('adults')
            kids = request.POST.get('kids')
            travel_class = request.POST.get('class')

            filtered_flights = []

            for flight in flights:
                if departure and flight['aeroport_depart_ref'] != int(departure):
                    continue
                if arrival and flight['aeroport_arrivee_ref'] != int(arrival):
                    continue
                if date and flight['date_depart'] != date:
                    continue
                if travel_class and flight['type'] != travel_class:
                    continue

                # If all conditions are satisfied, keep the flight
                filtered_flights.append(flight)

            flights = filtered_flights

            print(f"Flights : {flights}")

            return render(request, 'flights/flight_list.html', {'flights': flights, 'airports': airports})

        airports = requests.get('http://web-rest-4:8004/structure/infos/aeroports/')
        airports = airports.json()

        return render(request, 'general/index.html', {'airports': airports})
    
    def StaffHomePage(request):
        user = request.session.get('user')
        print(f"User : {user}")
        if user is not None:
            if user['is_superuser'] == True:
                return render(request, 'staff/general/index.html')
            else:
                return redirect('makarov_gp:home')
        else:
            #return to login page
            return redirect('makarov_gp:staff_login')

class FLIGHTS(TemplateView):
    def flightsPage(request, *args, **kwargs):

        airports = requests.get('http://web-rest-4:8004/structure/infos/aeroports/')
        airports = airports.json()
        #print(f"Airports : {airports}")

        flights = requests.get('http://web-rest-2:8002/vols/infos/')
        flights = flights.json()
        #print(f"Flights : {flights}")

        # Create a dictionary to quickly lookup airport names by id
        airport_dict = {airport['id']: airport['nom'] for airport in airports}

        # Add new attributes to each flight
        for flight in flights:
            flight['aeroport_depart_nom'] = airport_dict.get(flight['aeroport_depart_ref'], 'Unknown')
            flight['aeroport_arrivee_nom'] = airport_dict.get(flight['aeroport_arrivee_ref'], 'Unknown')


        if request.method == "POST":#If the user selected filters for the search
            print("POSTING THE FILTER FORM")

            print(f"Flights : {flights}")

            departure = request.POST.get('departure')
            arrival = request.POST.get('arrival')
            date = request.POST.get('date')
            adults = request.POST.get('adults')
            kids = request.POST.get('kids')
            travel_class = request.POST.get('class')

            # print(f"Departure: {departure}")
            # print(f"Arrival: {arrival}")
            # print(f"Date: {date}")
            # print(f"Adults: {adults}")
            # print(f"Kids: {kids}")
            # print(f"Travel Class: {travel_class}")

            filtered_flights = []

            for flight in flights:
                if departure and flight['aeroport_depart_ref'] != int(departure):
                    continue
                if arrival and flight['aeroport_arrivee_ref'] != int(arrival):
                    continue
                if date and flight['date_depart'] != date:
                    continue
                if travel_class and flight['type'] != travel_class:
                    continue

                # If all conditions are satisfied, keep the flight
                filtered_flights.append(flight)

            flights = filtered_flights

            print(f"Flights : {flights}")

        return render(request, 'flights/flight_list.html', {'flights': flights, 'airports': airports})

    def flights_user(request):
        user = request.session.get('user')
        if user:
            userName = user.get('username')
            print(f"User ID : {userName}")

            #Make the api call to get all of the user's reservations.
            reservations = requests.get(f'http://web-rest-3:8003/reservations/infos/user_vols/?user_ref={userName}')
            reservations = reservations.json()

            combined_reservations = []#Holds each pair reservation/vol

            #Now we concatenate the reservation and the flight details
            for reservation in reservations:
                vol_associe = requests.get(f'http://web-rest-2:8002/vols/infos/?numvol={reservation["vol_ref"]}')
                vol_associe = vol_associe.json()

                # print(f"vol associe : {vol_associe}")
                # print(f"Aeroport depart : {vol_associe[0]['aeroport_depart_ref']}")
                # print(f"Aeroport arrivee : {vol_associe[0]['aeroport_arrivee_ref']}")

                #This part below is just here to retrieve each airport's name
                departure_airport = requests.get(f'http://web-rest-4:8004/structure/infos/aeroports/{vol_associe[0]["aeroport_depart_ref"]}/')
                departure_airport_data = departure_airport.json()
                arrival_airport = requests.get(f'http://web-rest-4:8004/structure/infos/aeroports/{vol_associe[0]["aeroport_arrivee_ref"]}/')
                arrival_airport_data = arrival_airport.json()

                vol_associe[0]['aeroport_depart_nom'] = departure_airport_data['nom']
                vol_associe[0]['aeroport_arrivee_nom'] = arrival_airport_data['nom']

                combined_data = {**reservation, **vol_associe[0]}  # Assuming vol_associe returns a list with one dictionary
                combined_reservations.append(combined_data)
                
            #print(f"Reservations + Vols : {combined_reservations}")

            return render(request, 'flights/user_flights.html', {"c_reservations": combined_reservations})
        else:
            return redirect('makarov_gp:home')

    def buy_ticket(request, flight_id):#flight_id is the flight number (numvol)
        #Make the api call here to get the flight details

        user = request.session.get('user')
        if user is None:
            message = "You need to be logged-in in order to book a flight !"
            alert = "alert alert-warning"
            return render(request, "flights/message_confirmation.html", {'message': message, 'alert_style': alert})

        response = requests.get(f'http://web-rest-2:8002/vols/infos/?numvol={flight_id}')
        flight = response.json()
        flight = flight[0]
        
        print(f"Flight : {flight}")

        #Now we get the name for the departure and arrival airports
        departure_airport = requests.get(f'http://web-rest-4:8004/structure/infos/aeroports/{flight["aeroport_depart_ref"]}/')
        departure_airport_data = departure_airport.json()

        arrival_airport = requests.get(f'http://web-rest-4:8004/structure/infos/aeroports/{flight["aeroport_arrivee_ref"]}/')
        arrival_airport_data = arrival_airport.json()

        flight['aeroport_depart_nom'] = departure_airport_data['nom']
        flight['aeroport_arrivee_nom'] = arrival_airport_data['nom']

        #Now we render the page with all these infos to inform the user the flight has been booked !
        result = publish_reservation(flight_id, request.session.get('user').get('username'))
        print(f"Result unflitered : {result}")
        try:
            result = json.loads(result)
            if result['status'] == 'True':
                return render(request, 'flights/flight_detail.html', {'flight': flight})
            else:
                message = "Your bank rejected the payement."
                alert = "alert alert-warning"
                return render(request, "flights/message_confirmation.html", {'message': message, 'alert_style': alert})
        except json.decoder.JSONDecodeError:
            message = "Your bank rejected the payement."
            alert = "alert alert-warning"
            return render(request, "flights/message_confirmation.html", {'message': message, 'alert_style': alert})
            
    def cancel_resa(request, flight_id):#flight_id is the flight number (numvol)
        flight_id = flight_id

        #make api call to service to cancel the reservation.

MAKAROV-AIRPORT/docker/djangopache-compose/makarov_gp/templates/staff/demands/show_demands.html
{% extends "staff/general/UI/base.html" %}

{% load static i18n %}

{% block page_title %}
    <title>Makarov Airlines - DEMANDS</title>
{% endblock page_title %}

{% block additionnal_imports %}
    <link href={% static "libs/assets/css/style-show-demands.css" %} rel="stylesheet">
{% endblock additionnal_imports %}

{% block content%}
  <div id="empty-div" style="min-height: 80px;"></div>

  <main>

    {% for demand in demands %}
        <div class="demand-card mt-3">

            <div class="row">
                <div class="info-container col-12">
                    <p><strong>Demand from :</strong> {{ demand.user_ref }}</p>
                    <a href={% url "makarov_gp:show_user_detail" userName=demand.user_ref %} class="" target="_blank">[see info]</a>
                </div>
            </div>
            <div class="row">
                <div class="info-container col-12">
                    <p><strong>Flight : </strong>{{ demand.vol_ref }}</p>
                    <a href={% url "makarov_gp:show_flight_detail" numvol=demand.vol_ref %} target="_blank">[see info]</a>
                </div>
            </div>
            <div class="row">
                <div class="buttons col-12">
                    <a href={% url "makarov_gp:validate_demand" numvol=demand.vol_ref username=demand.user_ref %}><button class="btn btn-success">Accept</button></a>
                    <a href={% url "makarov_gp:reject_demand" numvol=demand.vol_ref username=demand.user_ref %}><button class="btn btn-danger">Reject</button></a>
                </div>
            </div>
        </div>
    {% endfor %}

  </main>
    
  <div id="empty-div" style="min-height: 80px;"></div>

  {% if message %}
  <script>
    alert("{{ message }}");
  </script>
  {% endif %}


{% endblock content%}

MAKAROV-AIRPORT/docker/djangopache-compose/makarov_gp/templates/staff/demands/show_flight_details.html
{% extends "staff/general/UI/base.html" %}

{% load static i18n %}

{% block page_title %}
    <title>Makarov Airlines - USER</title>
{% endblock page_title %}

{% block additionnal_imports %}
    <link href={% static "libs/assets/css/user_detail.css" %} rel="stylesheet">
{% endblock additionnal_imports %}

{% block content%}
  <div id="empty-div" style="min-height: 80px;"></div>

  <main>
    <h4>Flight N°{{ flight.numvol }}</h4>
    <div class="row">
        <div class="fn-container col-6">
            <p><strong>FROM :</strong> {{ flight.aeroport_depart_nom }}</p>
        </div>
        <div class="fn-container col-6">
            <p><strong>TO :</strong> {{ flight.aeroport_arrivee_nom }}</p>
        </div>
    <div>
    <div class="row">
        <div class="fn-container col-6">
            <p><strong>Departure date :</strong> {{ flight.date_depart }}</p>
        </div>
        <div class="fn-container col-6">
            <p><strong>Arrival Date :</strong> {{ flight.date_arrivee }}</p>
        </div>
    <div>
    <div class="row">
        <div class="fn-container col-6">
            <p><strong>Departure time :</strong> {{ flight.heure_depart }}</p>
        </div>
        <div class="fn-container col-6">
            <p><strong>Arrival time :</strong> {{ flight.heure_arrivee }}</p>
        </div>
    <div>
    <div class="row">
        <div class="fn-container col-4">
            <p><strong>Departure time :</strong> {{ flight.prix }}</p>
        </div>
        <div class="fn-container col-4">
            <p><strong>Arrival time :</strong> {{ flight.avion_ref }}</p>
        </div>
        <div class="fn-container col-4">
            <p><strong>Arrival time :</strong> {{ flight.type }}</p>
        </div>
    <div>
  </main>
    
  <div id="empty-div" style="min-height: 80px;"></div>

  {% if message %}
  <script>
    alert("{{ message }}");
  </script>
  {% endif %}


{% endblock content%}

MAKAROV-AIRPORT/docker/djangopache-compose/makarov_gp/templates/staff/demands/show_user_details.html
{% extends "staff/general/UI/base.html" %}

{% load static i18n %}

{% block page_title %}
    <title>Makarov Airlines - USER</title>
{% endblock page_title %}

{% block additionnal_imports %}
    <link href={% static "libs/assets/css/user_detail.css" %} rel="stylesheet">
{% endblock additionnal_imports %}

{% block content%}
  <div id="empty-div" style="min-height: 80px;"></div>

  <main>
    <h4>User N°{{ user.id }}</h4>
    <div class="row">
        <div class="info-container col-12">
            <p><strong>Username :</strong> {{ user.username }}</p>
        </div>
    <div>
    <div class="row">
        <div class="info-container col-12">
            <p><strong>Email :</strong> {{ user.email }}</p>
        </div>
    </div>
    <div class="row">
        <div class="fn-container col-6">
            <p><strong>First Name :</strong> {{ user.first_name }}</p>
        </div>
        <div class="fn-container col-6">
            <p><strong>Last Name :</strong> {{ user.last_name }}</p>
        </div>
    </div>
    <div class="row">
        <div class="info-container col-12">
            <p><strong>Is Staff :</strong> {% if user.is_superuser == True %}YES {% else %} NO{% endif %}</p>
        </div>
    </div>
  </main>
    
  <div id="empty-div" style="min-height: 80px;"></div>

  {% if message %}
  <script>
    alert("{{ message }}");
  </script>
  {% endif %}


{% endblock content%}